# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInputClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InputUrl', models.URLField(unique=True)),
                ('ShortenedKey', models.CharField(max_length=100)),
            ],
        ),
    ]
